name: Publish package to the Maven Central Repository
on:
  push:
    branches:
      - main
jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Install gpg secret key
        run: |
          echo "${{ secrets.MAVEN_GPG_SECRET_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: | 
           mvn  \
           --no-transfer-progress  \
           --batch-mode \
           -Dgpg.passphrase=${{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }} \
           -Dgpg.keyname=${{ secrets.MAVEN_GPG_SECRET_KEY_NAME }} \
           clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
